In [1]:
import pandas as pd
import numpy as np

a = pd.Series([12,2,23,14,5], index=["ali","irfan","ahmed","hassan","bilal"])
a.sort_values(ascending=False)
type(a)

pandas.Series

In [2]:
b = pd.Series({"ali":10,"irfan":12, "ahmed":31, "hassan":14, "bilal":5})
b.sort_values(ascending=False)

ahmed     31
hassan    14
irfan     12
ali       10
bilal      5
dtype: int64

In [3]:
c = pd.DataFrame({
    "name":["ali","irfan","ahmed","hassan","bilal"],
    "age":[20,21,22,23,24],
    "city":["karachi","lahore","islamabad","quetta","peshawar"],
    "marks":[90,80,70,60,50]
},
index=["a","b","c","d","e"]
)
print(c)
print(c.columns)
print(c.index)
print(c.sort_values(by="marks"))

     name  age       city  marks
a     ali   20    karachi     90
b   irfan   21     lahore     80
c   ahmed   22  islamabad     70
d  hassan   23     quetta     60
e   bilal   24   peshawar     50
Index(['name', 'age', 'city', 'marks'], dtype='str')
Index(['a', 'b', 'c', 'd', 'e'], dtype='str')
     name  age       city  marks
e   bilal   24   peshawar     50
d  hassan   23     quetta     60
c   ahmed   22  islamabad     70
b   irfan   21     lahore     80
a     ali   20    karachi     90


In [4]:
bs_result = pd.read_csv("bs_english_2025.csv",delimiter=",")
bs_result.shape
bs_result.index
bs_result.info()


<class 'pandas.DataFrame'>
RangeIndex: 11 entries, 0 to 10
Data columns (total 16 columns):
 #   Column                                Non-Null Count  Dtype  
---  ------                                --------------  -----  
 0   student_name                          11 non-null     str    
 1   father_name                           11 non-null     str    
 2   gender                                11 non-null     str    
 3   18th_century_english_novel            11 non-null     int64  
 4   islamic_studies                       11 non-null     int64  
 5   understanding_holy_quran_1            11 non-null     int64  
 6   history_of_english_literature         11 non-null     int64  
 7   intro_to_literary_devices_and_genres  11 non-null     int64  
 8   functional_english                    11 non-null     int64  
 9   applications_of_ict                   11 non-null     int64  
 10  obt_marks                             11 non-null     int64  
 11  total_marks                     

In [5]:

df = bs_result.describe()
print(df)
round(df.iloc[1,0:7],2).sort_values(ascending=False)
round(df.iloc[1,0:7],2).sort_values(ascending=False)

# df['18th_century_english_novel']

       18th_century_english_novel  islamic_studies  \
count                   11.000000        11.000000   
mean                    76.636364        81.545455   
std                      8.213072         6.470914   
min                     67.000000        74.000000   
25%                     69.000000        76.500000   
50%                     78.000000        78.000000   
75%                     83.000000        87.000000   
max                     90.000000        91.000000   

       understanding_holy_quran_1  history_of_english_literature  \
count                   11.000000                      11.000000   
mean                    86.727273                      68.818182   
std                      4.880387                       8.623435   
min                     79.000000                      55.000000   
25%                     85.000000                      63.000000   
50%                     87.000000                      67.000000   
75%                     89.000000    

understanding_holy_quran_1              86.73
islamic_studies                         81.55
18th_century_english_novel              76.64
applications_of_ict                     74.73
history_of_english_literature           68.82
intro_to_literary_devices_and_genres    63.82
functional_english                      62.55
Name: mean, dtype: float64

In [6]:
bs_result

,student_name,father_name,gender,18th_century_english_novel,islamic_studies,understanding_holy_quran_1,history_of_english_literature,intro_to_literary_devices_and_genres,functional_english,applications_of_ict,obt_marks,total_marks,percentage_of_obt_marks,cr_hrs,overall_cgpa,promoted
0,khadija javed,javed zafar,female,90,75,79,64,68,61,78,515,700,73.57,18,3.40,1
1,aiman laraib,ashfaq ahmed,female,82,74,86,74,74,63,77,530,700,75.71,18,3.59,1
2,shameen iqbal,muhammad zafar iqbal,female,84,78,84,73,76,72,84,551,700,78.71,18,3.77,1
3,sidra kainat,malik fazal ur rehman,female,82,76,90,84,81,67,82,562,700,80.29,18,3.82,1
4,sumaira bibi,malik khair muhammad,female,70,78,88,55,52,43,70,456,700,65.14,18,2.71,1
5,ruqiya noreen,attaullah khan,female,84,91,87,80,76,72,82,572,700,81.71,18,3.86,1
6,jamila bibi,rafiullah khan,female,78,91,96,67,63,77,77,549,700,78.43,18,3.57,1
7,sadia bibi,shujaudin,female,69,77,87,62,54,62,68,479,700,68.43,18,3.02,1
8,malik sheeraz,muhammad faiz ullah,male,69,88,88,72,62,61,70,510,700,72.86,18,3.25,1
9,muhammad zain ahad,israr muhammad amjad,male,67,86,79,64,48,62,68,474,700,67.71,18,2.97,1


In [7]:
# bins: (F: -infinity to 49](C:50-59]
# 0-49 D | 50-54 C- | 55-59 C | 60-64 C+ | 65-69 B- | 70-74 B | 75-79 B+ | 80-84 A | 85+ A+|  

bins = [-np.inf, 49,54,59,64,69,74,79,84,np.inf]
labels = ['D','C-','C','C+','B-','B','B+','A','A+']

#pd.cut(bs_result.iloc[0,3:10],bins=bins, labels=labels)
#pd.cut(bs_result,bins=bins, labels=labels)



In [8]:
#performance tiering
#student between 3.5 to 4
#best_performers = bs_result[bs_result['overall_cgpa']>3.5]
best_performers = bs_result.nlargest(5,"overall_cgpa")[["student_name","overall_cgpa","obt_marks","total_marks","percentage_of_obt_marks"]]
best_performers

,student_name,overall_cgpa,obt_marks,total_marks,percentage_of_obt_marks
5,ruqiya noreen,3.86,572,700,81.71
3,sidra kainat,3.82,562,700,80.29
2,shameen iqbal,3.77,551,700,78.71
1,aiman laraib,3.59,530,700,75.71
6,jamila bibi,3.57,549,700,78.43


In [9]:
worst_performers = bs_result.nsmallest(5,"overall_cgpa")[["student_name","overall_cgpa","obt_marks","total_marks","percentage_of_obt_marks"]]
worst_performers

,student_name,overall_cgpa,obt_marks,total_marks,percentage_of_obt_marks
4,sumaira bibi,2.71,456,700,65.14
10,aimal aslam,2.77,465,700,66.43
9,muhammad zain ahad,2.97,474,700,67.71
7,sadia bibi,3.02,479,700,68.43
8,malik sheeraz,3.25,510,700,72.86


In [10]:
bool_sub = bs_result.iloc[0,3:10]<50
print(bool_sub.sum())

0


In [11]:
bool_subj = bs_result.iloc[4,3:10]<50
bool_subj.value_counts()

4
False    6
True     1
Name: count, dtype: int64

In [12]:
#students with most failed subjects
st_failed_sub = []
st_names = []
print("|Student Name |--|Failed Subjects|")
for st in range(0,11): 
    bool_fail_sub = bs_result.iloc[st,3:10]<50
    st_failed_sub.append(bool_fail_sub.sum())
    st_names.append(bs_result.iloc[st,0])

st_failed_sub1 = pd.Series(st_failed_sub,index=st_names)
st_failed_sub1

|Student Name |--|Failed Subjects|


khadija javed         0
aiman laraib          0
shameen iqbal         0
sidra kainat          0
sumaira bibi          1
ruqiya noreen         0
jamila bibi           0
sadia bibi            0
malik sheeraz         0
muhammad zain ahad    1
aimal aslam           2
dtype: int64

In [13]:
#students name ------> failed subjects

# type(bool_fail_sub)
# bool_fail_sub = bs_result.iloc[4,2:9]<50
# print(bool_fail_sub.index)

# for st2 in range(0,11):
bool_fail_sub = bs_result.iloc[4,3:10]<50
print(bool_fail_sub[bool_fail_sub])
print(bs_result.iloc[4,0],bool_fail_sub[bool_fail_sub].index)
# subj
#best performaning subjects
#worst performing subjects

functional_english    True
Name: 4, dtype: bool
sumaira bibi Index(['functional_english'], dtype='str')


In [14]:
# print(len(bs_result.columns))
# print(len(bs_result.columns))
data =[]
d_index=[]
col = bs_result.columns
print("Subjects|                          |Average Marks|")
for m in range(3,10):
  # print(f"{col[m]} {round(bs_result[col[m]].mean(),2)}")
  data.append(round(bs_result[col[m]].mean(),2))
  d_index.append(col[m])

sub = pd.Series(data,index=d_index)
print(sub.sort_values(ascending=False))


Subjects|                          |Average Marks|
understanding_holy_quran_1              86.73
islamic_studies                         81.55
18th_century_english_novel              76.64
applications_of_ict                     74.73
history_of_english_literature           68.82
intro_to_literary_devices_and_genres    63.82
functional_english                      62.55
dtype: float64


In [15]:
bs_result.nlargest(5,"understanding_holy_quran_1")[['student_name','understanding_holy_quran_1']]
print(bs_result.nlargest(7,"applications_of_ict")[['student_name','applications_of_ict']])
# of students with higher than average
avg_ict = bs_result['applications_of_ict'].mean()
print("ICT avg marks: ",avg_ict.round(1))
above_avg = bs_result[bs_result['applications_of_ict']>avg_ict][['student_name','applications_of_ict']].sort_values(by="applications_of_ict", ascending=False)
below_avg = bs_result[bs_result['applications_of_ict']<avg_ict][['student_name','applications_of_ict']].sort_values(by="applications_of_ict", ascending=False)
print(f"ICT Above Avg. {above_avg.shape[0]}/{bs_result.shape[0]} = {round(above_avg.shape[0]/bs_result.shape[0]*100,1)}%")
print(below_avg)

    student_name  applications_of_ict
2  shameen iqbal                   84
3   sidra kainat                   82
5  ruqiya noreen                   82
0  khadija javed                   78
1   aiman laraib                   77
6    jamila bibi                   77
4   sumaira bibi                   70
ICT avg marks:  74.7
ICT Above Avg. 6/11 = 54.5%
          student_name  applications_of_ict
4         sumaira bibi                   70
8        malik sheeraz                   70
7           sadia bibi                   68
9   muhammad zain ahad                   68
10         aimal aslam                   66


In [16]:
data =[]
d_index=[]
col = bs_result.columns
print("__________|Subjects|_________________| Failed Students|_____")
for m in range(3,10):
  # print(f"{col[m]} {round(bs_result[col[m]].mean(),2)}")
  fa = bs_result[bs_result[col[m]]<50]
  data.append(fa.shape[0])
  d_index.append(col[m])

sub = pd.Series(data,index=d_index)
print(sub.sort_values(ascending=False))

__________|Subjects|_________________| Failed Students|_____
intro_to_literary_devices_and_genres    2
functional_english                      2
18th_century_english_novel              0
understanding_holy_quran_1              0
islamic_studies                         0
history_of_english_literature           0
applications_of_ict                     0
dtype: int64


students ----> # of failed subjects

In [17]:
bs_result.iloc[0]['islamic_studies']<50
(bs_result.iloc[0,3:10]<50).sum()
# bs_result['student_name']

np.int64(0)

In [18]:
bs_result.functional_english.value_counts()
bs_result['functional_english'].value_counts()

functional_english
61    2
72    2
62    2
63    1
67    1
43    1
77    1
48    1
Name: count, dtype: int64

In [19]:
bs_result.describe()

,18th_century_english_novel,islamic_studies,understanding_holy_quran_1,history_of_english_literature,intro_to_literary_devices_and_genres,functional_english,applications_of_ict,obt_marks,total_marks,percentage_of_obt_marks,cr_hrs,overall_cgpa,promoted
count,11.000000,11.000000,11.000000,11.000000,11.000000,11.000000,11.000000,11.000000,11.0,11.000000,11.0,11.000000,11.0
mean,76.636364,81.545455,86.727273,68.818182,63.818182,62.545455,74.727273,514.818182,700.0,73.544545,18.0,3.339091,1.0
std,8.213072,6.470914,4.880387,8.623435,12.056684,10.033580,6.512924,41.373465,0.0,5.910478,0.0,0.421176,0.0
min,67.000000,74.000000,79.000000,55.000000,48.000000,43.000000,66.000000,456.000000,700.0,65.140000,18.0,2.710000,1.0
25%,69.000000,76.500000,85.000000,63.000000,53.000000,61.000000,69.000000,476.500000,700.0,68.070000,18.0,2.995000,1.0
50%,78.000000,78.000000,87.000000,67.000000,63.000000,62.000000,77.000000,515.000000,700.0,73.570000,18.0,3.400000,1.0
75%,83.000000,87.000000,89.000000,73.500000,75.000000,69.500000,80.000000,550.000000,700.0,78.570000,18.0,3.680000,1.0
max,90.000000,91.000000,96.000000,84.000000,81.000000,77.000000,84.000000,572.000000,700.0,81.710000,18.0,3.860000,1.0


In [20]:
bs_result[['student_name','obt_marks']].groupby(['student_name']).mean()

,obt_marks
student_name,
aimal aslam,465.0
aiman laraib,530.0
jamila bibi,549.0
khadija javed,515.0
malik sheeraz,510.0
muhammad zain ahad,474.0
ruqiya noreen,572.0
sadia bibi,479.0
shameen iqbal,551.0


In [21]:
sub1_c = bs_result['18th_century_english_novel'].between(60,70).sum()
sub1_c

np.int64(5)

In [22]:
subject_cols = [
    "18th_century_english_novel",
    "islamic_studies",
    "understanding_holy_quran_1",
    "history_of_english_literature",
    "intro_to_literary_devices_and_genres",
    "functional_english",
    "applications_of_ict",
]

# 1. Reshape dataframe from wide to long format
df_long = bs_result.melt(
    id_vars=["student_name"],
    value_vars=subject_cols,
    var_name="subject",
    value_name="marks",
)
print(df_long)
# 2. Filter subjects where marks are less than 50 (Fail)
failed_df = df_long[df_long["marks"] < 50]

# 3. Group by student name and join subject names
result = (
    failed_df.groupby("student_name")["subject"]
    .apply(lambda x: ", ".join(x))
    .reset_index()
)

# Rename columns for clarity
result.columns = ["Student Name", "Failed Subject(s)"]

print(result.to_string(index=False))

          student_name                     subject  marks
0        khadija javed  18th_century_english_novel     90
1         aiman laraib  18th_century_english_novel     82
2        shameen iqbal  18th_century_english_novel     84
3         sidra kainat  18th_century_english_novel     82
4         sumaira bibi  18th_century_english_novel     70
..                 ...                         ...    ...
72         jamila bibi         applications_of_ict     77
73          sadia bibi         applications_of_ict     68
74       malik sheeraz         applications_of_ict     70
75  muhammad zain ahad         applications_of_ict     68
76         aimal aslam         applications_of_ict     66

[77 rows x 3 columns]
      Student Name                                        Failed Subject(s)
       aimal aslam intro_to_literary_devices_and_genres, functional_english
muhammad zain ahad                     intro_to_literary_devices_and_genres
      sumaira bibi                                   

In [23]:
print(bs_result.groupby("gender")['promoted'].value_counts())
print(bs_result.groupby("gender")['promoted'].sum())
print(bs_result.gender.value_counts())
print(bs_result.gender.sum())
print(bs_result.promoted.value_counts())

gender  promoted
female  1           9
male    1           2
Name: count, dtype: int64
gender
female    9
male      2
Name: promoted, dtype: int64
gender
female    9
male      2
Name: count, dtype: int64
femalefemalefemalefemalefemalefemalefemalefemalemalemalefemale
promoted
1    11
Name: count, dtype: int64


In [24]:
#students with gpa above than 3
gpa_above_3 = bs_result[bs_result['overall_cgpa']>3]
print("Students with CGPA>3:",gpa_above_3.shape[0])
gpa_above_3[['gender']].groupby(["gender"]).value_counts()

Students with CGPA>3: 8


gender
female    7
male      1
Name: count, dtype: int64

In [25]:
#gpa band using filtering

below_3 = bs_result[bs_result['overall_cgpa']<3][['student_name','overall_cgpa']]
print("\n================================")
print("CGPA: < 3: ",below_3.shape[0])
print(round(below_3.shape[0]/bs_result.shape[0]*100,1),"%")
print(below_3)

bet_3_35 = bs_result[bs_result['overall_cgpa'].between(3,3.5)][['student_name','overall_cgpa']]
print("\n================================")
print("CGPA: 3 - 4: ",bet_3_35.shape[0])
print(round(bet_3_35.shape[0]/bs_result.shape[0]*100,1),"%")
print(bet_3_35)

bet_35_4 = bs_result[bs_result['overall_cgpa'].between(3.5,4)][['student_name','overall_cgpa']]
print("\n================================")
print("CGPA: 3.5 - 4: ",bet_35_4.shape[0])
print(round(bet_35_4.shape[0]/bs_result.shape[0]*100,1),"%")
print(bet_35_4)



CGPA: < 3:  3
27.3 %
          student_name  overall_cgpa
4         sumaira bibi          2.71
9   muhammad zain ahad          2.97
10         aimal aslam          2.77

CGPA: 3 - 4:  3
27.3 %
    student_name  overall_cgpa
0  khadija javed          3.40
7     sadia bibi          3.02
8  malik sheeraz          3.25

CGPA: 3.5 - 4:  5
45.5 %
    student_name  overall_cgpa
1   aiman laraib          3.59
2  shameen iqbal          3.77
3   sidra kainat          3.82
5  ruqiya noreen          3.86
6    jamila bibi          3.57


In [26]:
# Subject with most number of A grades
subj = []
ap_grades = []
a_grades = []
f_grades = []
for i in range(3,10):
    sub = bs_result.columns[i]
    subj.append(sub)
    ap_grades.append(bs_result[bs_result[sub]>=80].shape[0])
    f_grades.append(bs_result[bs_result[sub]<50].shape[0])
    # b_grades.append(bs_result[bs_result[sub].between(70,79)].shape[0])

report_a_grades = pd.DataFrame({
    "Subjects":subj,
    "A & above":ap_grades,
    "Fail":f_grades
    # "B":b_grades
})
print(report_a_grades.sort_values(by="A & above", ascending=False))
# print(report_a_grades)
# print(a_grades)

# bs_result.columns[3]

                               Subjects  A & above  Fail
2            understanding_holy_quran_1          9     0
0            18th_century_english_novel          5     0
1                       islamic_studies          5     0
6                   applications_of_ict          3     0
3         history_of_english_literature          2     0
4  intro_to_literary_devices_and_genres          1     2
5                    functional_english          0     2


In [27]:
st = []
fail_sub = []
a_and_above = []
cgpa = []
min_marks = []
max_marks = []


for i in range(11):
    st.append(bs_result.iloc[i,0])
    fail_sub.append((bs_result.iloc[i,3:10]<50).sum())
    a_and_above.append((bs_result.iloc[i,3:10]>=80).sum())
    cgpa.append((bs_result.loc[i,"overall_cgpa"]))
    min_marks.append((bs_result.iloc[i,3:10].min()))
    max_marks.append((bs_result.iloc[i,3:10].max()))

rp_fs = pd.DataFrame({
    "student name":st,
    "failed subjects":fail_sub,
    "A & above":a_and_above,
    "CGPA":cgpa,
    "Minimum Marks":min_marks,
    "Maximum Marks":max_marks
})
rp_fs.sort_values(by="CGPA",ascending=False)
# print(fail_sub)

,student name,failed subjects,A & above,CGPA,Minimum Marks,Maximum Marks
5,ruqiya noreen,0,5,3.86,72,91
3,sidra kainat,0,5,3.82,67,90
2,shameen iqbal,0,3,3.77,72,84
1,aiman laraib,0,2,3.59,63,86
6,jamila bibi,0,2,3.57,63,96
0,khadija javed,0,1,3.40,61,90
8,malik sheeraz,0,2,3.25,61,88
7,sadia bibi,0,1,3.02,54,87
9,muhammad zain ahad,1,1,2.97,48,86
10,aimal aslam,2,2,2.77,48,90


In [ ]:
avg1= bs_result.iloc[0,3:10].mean()
# print(bs_result.iloc[0,0])
# print(avg1.round(1))
# print(bs_result.iloc[0,3:10])
sub_bool = bs_result.iloc[0,3:10]<avg1
final = sub_bool[sub_bool]
# print("\nfinal: ",len(final))
# print("final: ",final.index)
# print("final: ",len(final.index))
# print("final: ",final.index[0])
# print(sub_bool)
# print(type(sub_bool))
# print(sub_bool.index)
# print(sub_bool.values)

st_name = []
weak_subj = np.empty((11,7))
ws_arr = np.array([])
strong_sub = []
print(weak_subj)

for i in range(11):
    st_name.append(bs_result.iloc[i,0])
    print(bs_result.iloc[i,0])
    sub_bool = bs_result.iloc[i,3:10]<65
    sub1 = sub_bool[sub_bool]

    if len(sub1)>0:
        for j in range(len(sub1)):
            sj = sub1.index[j]
            ws = sj+": "+str(bs_result.loc[i,sj])
            np.append(ws_arr,ws)
    else:
        np.append(ws_arr,"nil")

    for i in range(11):
        for j in range(7):
            np.insert(weak_subj, weak_subj[i][j], ws_arr, axis=0)
    
# print("\n",bs_result.loc[0,sj])    
# print(bs_result[sub1.index[0]])
# print(sub_.index[0])
print(type(weak_subj))
print(weak_subj)

# rep = pd.DataFrame({
#     "student name":st_name,
#     "weak subjects":weak_subj
# })
print(len(st_name))
print(len(weak_subj))


[[0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]
khadija javed


AttributeError: 'numpy.ndarray' object has no attribute 'index'

In [55]:
weak_subj = np.full((11, 7), "nil", dtype=object)
st_name = []
# print(weak_subj)
for i in range(11):
    st_name.append(bs_result.iloc[i, 0])
    scores = bs_result.iloc[i, 3:10]
    # print(scores)
    # Find positions where marks are less than 65
    weak_mask = scores < 65
    # print(scores[weak_mask])
    col_idx = 0
    for subj_name, score in scores[weak_mask].items():
        weak_subj[i, col_idx] = f"{subj_name}: {score}"
        col_idx += 1

print(len(weak_subj))
print(weak_subj.shape)
print(len(st_name))

data = []
for i in range(11):
    data.append({
        'Student':st_name[i],
        "Weak Subject":weak_subj[i]
    })
rep = pd.DataFrame(data)
rep


11
(11, 7)
11


,Student,Weak Subject
0,khadija javed,"[history_of_english_literature: 64, functional..."
1,aiman laraib,"[functional_english: 63, nil, nil, nil, nil, n..."
2,shameen iqbal,"[nil, nil, nil, nil, nil, nil, nil]"
3,sidra kainat,"[nil, nil, nil, nil, nil, nil, nil]"
4,sumaira bibi,"[history_of_english_literature: 55, intro_to_l..."
5,ruqiya noreen,"[nil, nil, nil, nil, nil, nil, nil]"
6,jamila bibi,"[intro_to_literary_devices_and_genres: 63, nil..."
7,sadia bibi,"[history_of_english_literature: 62, intro_to_l..."
8,malik sheeraz,"[intro_to_literary_devices_and_genres: 62, fun..."
9,muhammad zain ahad,"[history_of_english_literature: 64, intro_to_l..."
